import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import Menu from "./Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-black text-white flex gap-2 mx-auto max-w-6xl mt-5`}
      >
        <Menu />
        <div className="flex-grow">{children}</div>
      </body>
    </html>
  );
}
